services:

    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - 8100:80
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/conf.d/custom.ini
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        container_name: mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - 3306:3306
        environment:            
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-grupo47}'
            MYSQL_USER: '${DB_USERNAME:-grupo47}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-grupo47}'
            MYSQL_EMPTY_ROOT_PASSWORD: "yes"
        volumes:
            - './docker/database/volumes/mysql/:/var/lib/mysql'
        healthcheck:
            test:
                ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 20
            timeout: 5s
            interval: 30s