output "AWS_COGNITO_USER_POOL_WEB_CLIENT_ID" {
  value = var.AWS_COGNITO_USER_POOL_WEB_CLIENT_ID
}

output "AWS_COGNITO_USER_POOL_WEB_CLIENT_SECRET" {
  value     = var.AWS_COGNITO_USER_POOL_WEB_CLIENT_SECRET
  sensitive = true
}

output "AWS_COGNITO_USER_POOL_API_CLIENT_ID" {
  value = var.AWS_COGNITO_USER_POOL_API_CLIENT_ID
}

output "AWS_COGNITO_USER_POOL_API_CLIENT_SECRET" {
  value     = var.AWS_COGNITO_USER_POOL_API_CLIENT_SECRET
  sensitive = true
}
