apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fpm
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
      - name: migrations
        image: lucasminikel/fpm_server:v0.0.1
        command:
        - php
        args:
        - artisan
        - migrate
        - --force
        envFrom:
        - configMapRef:
            name: cm-common
        - secretRef:
            name: secret-common
      containers:
      - name: fpm
        image: lucasminikel/fpm_server:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: cm-common
        - secretRef:
            name: secret-common
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
