apiVersion: v1
kind: Service
metadata:
  name: svc-fpm
  labels:
    tier: backend
    layer: webserver
spec:
  selector:
    tier: backend
    layer: fpm
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
