apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database
  labels:
    tier: backend
    layer: database
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
