apiVersion: v1
kind: Service
metadata:
  name: svc-database
  labels:
    tier: backend
    layer: database
spec:
  selector:
    tier: backend
    layer: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30036
  type: NodePort
