apiVersion: v1
kind: Service
metadata:
  name: svc-webserver
  labels:
    tier: backend
    layer: webserver
spec:
  selector:
    tier: backend
    layer: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
